services:
  # Координатор - главный узел кластера
  vecdb-coordinator:
    build: .
    container_name: vecdb-coordinator
    hostname: coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./coordinator_data:/app/storage
      - ./configs/config-coordinator.json:/app/config.json:ro
    user: "1000:1000"
    environment:
      - RUST_LOG=info
      - HOSTNAME=coordinator
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - vecdb-cluster
    restart: "no"
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Шард 1
  vecdb-shard1:
    build: .
    container_name: vecdb-shard1
    hostname: shard1
    ports:
      - "8081:8081"
    volumes:
      - ./shard1_data:/app/storage
      - ./configs/config-shard1.json:/app/config.json:ro
    user: "1000:1000"
    environment:
      - RUST_LOG=info
      - HOSTNAME=shard1
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - vecdb-cluster
    restart: "no"
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Шард 2
  vecdb-shard2:
    build: .
    container_name: vecdb-shard2
    hostname: shard2
    ports:
      - "8082:8082"
    volumes:
      - ./shard2_data:/app/storage
      - ./configs/config-shard2.json:/app/config.json:ro
    user: "1000:1000"
    environment:
      - RUST_LOG=info
      - HOSTNAME=shard2
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - vecdb-cluster
    restart: "no"
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Мониторинг кластера
  cluster-monitor:
    image: nginx:alpine
    container_name: vecdb-monitor
    ports:
      - "9090:80"
    volumes:
      - ./monitoring/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vecdb-cluster
    depends_on:
      - vecdb-coordinator
      - vecdb-shard1
      - vecdb-shard2
    restart: "no"

networks:
  vecdb-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
